name: WireGuard Easy
package: lazycat.community.app.wg-easy
version: 15.1.0
min_os_version: 1.3.8
description: "the easiest way to install & manage WireGuard on any Linux host"
homepage: https://github.com/wg-easy/wg-easy
author: wg-easy
application:
    subdomain: wg-easy
    background_task: true
    public_path:
        - /

    upstreams:
        - location: /
          backend: http://wg-easy:51821/

    ingress:
        - protocol: tcp
          port: 51820
          service: wg-easy

services:
    wg-easy:
        # ghcr.io/wg-easy/wg-easy:15.1.0
        image: registry.lazycat.cloud/czyt/wg-easy/wg-easy:038aee2eedc5dec3
        environment:
            - INSECURE=true
            - INIT_ENABLED=true
            - INIT_USERNAME={{.U.init_user_name}}
            - INIT_PASSWORD={{.U.init_user_password}}
            - INIT_PORT=51820
            - INIT_DNS={{.U.init_dns}}
            - INIT_IPV4_CIDR={{.U.init_ipv4_cidr}}
            - INIT_IPV6_CIDR={{.U.init_ipv6_cidr}}
{{if .U.enable_custom_domain}}
            - INIT_HOST={{.U.custom_domain}}
{{else}}
            - INIT_HOST={{.S.AppDomain}}
{{end}}
        netadmin: true
        binds:
            - /lzcapp/var/wireguard:/etc/wireguard

locales:
    zh:
        name: "WireGuard Easy"
        description: "最简单的方式在任何Linux主机上安装和管理WireGuard"
    zh_CN:
        name: "WireGuard Easy"
        description: "最简单的方式在任何Linux主机上安装和管理WireGuard"
    en:
        name: "WireGuard Easy"
        description: "the easiest way to install & manage WireGuard on any Linux host"
